// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACPRX-hbRpst-neOeSUMww3K8vkA1MAmQ',
    appId: '1:62632677294:web:09cdbe7052b35f8701c23f',
    messagingSenderId: '62632677294',
    projectId: 'expense-flow-pro-e11c8',
    authDomain: 'expense-flow-pro-e11c8.firebaseapp.com',
    storageBucket: 'expense-flow-pro-e11c8.firebasestorage.app',
    measurementId: 'G-55ZLE8HG7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNB8ZgtTf_q_VPlkHPcu3QucvwvDMQoo',
    appId: '1:62632677294:android:3c57c6e88fd63b3d01c23f',
    messagingSenderId: '62632677294',
    projectId: 'expense-flow-pro-e11c8',
    storageBucket: 'expense-flow-pro-e11c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FttV_7sEtEpLYKRaOp7nDAgaCZmIIpM',
    appId: '1:62632677294:ios:c5002b35184fbebe01c23f',
    messagingSenderId: '62632677294',
    projectId: 'expense-flow-pro-e11c8',
    storageBucket: 'expense-flow-pro-e11c8.firebasestorage.app',
    iosBundleId: 'com.example.expenseFlowPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FttV_7sEtEpLYKRaOp7nDAgaCZmIIpM',
    appId: '1:62632677294:ios:c5002b35184fbebe01c23f',
    messagingSenderId: '62632677294',
    projectId: 'expense-flow-pro-e11c8',
    storageBucket: 'expense-flow-pro-e11c8.firebasestorage.app',
    iosBundleId: 'com.example.expenseFlowPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACPRX-hbRpst-neOeSUMww3K8vkA1MAmQ',
    appId: '1:62632677294:web:cd423e0356eb381701c23f',
    messagingSenderId: '62632677294',
    projectId: 'expense-flow-pro-e11c8',
    authDomain: 'expense-flow-pro-e11c8.firebaseapp.com',
    storageBucket: 'expense-flow-pro-e11c8.firebasestorage.app',
    measurementId: 'G-DF4YVTVQMD',
  );
}
