// Mocks generated by Mockito 5.4.6 from annotations
// in expence_flow_pro/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i15;

import 'package:expence_flow_pro/database/app_database.dart' as _i9;
import 'package:expence_flow_pro/features/auth/repository/auth_repository.dart'
    as _i5;
import 'package:expence_flow_pro/features/budget/controller/budget_controller.dart'
    as _i16;
import 'package:expence_flow_pro/features/budget/model/budget_model.dart'
    as _i17;
import 'package:expence_flow_pro/features/expense/model/expense_model.dart'
    as _i8;
import 'package:expence_flow_pro/features/expense/repository/expense_repository.dart'
    as _i7;
import 'package:expence_flow_pro/features/recurring/controller/recurring_controller.dart'
    as _i18;
import 'package:expence_flow_pro/features/recurring/model/recurring_model.dart'
    as _i19;
import 'package:expence_flow_pro/features/transfer/model/transfer_model.dart'
    as _i21;
import 'package:expence_flow_pro/features/transfer/repository/transfer_repository.dart'
    as _i20;
import 'package:expence_flow_pro/features/wallet/controller/wallet_controller.dart'
    as _i12;
import 'package:expence_flow_pro/features/wallet/model/wallet_model.dart'
    as _i11;
import 'package:expence_flow_pro/features/wallet/repository/wallet_repository.dart'
    as _i10;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:flutter/material.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_1<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake implements _i2.GlobalKey<T> {
  _FakeGlobalKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMetadata_3 extends _i1.SmartFake implements _i4.UserMetadata {
  _FakeUserMetadata_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_4 extends _i1.SmartFake implements _i4.MultiFactor {
  _FakeMultiFactor_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_5 extends _i1.SmartFake implements _i4.IdTokenResult {
  _FakeIdTokenResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_6 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_7 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_8 extends _i1.SmartFake implements _i4.User {
  _FakeUser_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i4.User?>.empty(),
      ) as _i6.Stream<_i4.User?>);

  @override
  _i6.Future<_i4.User?> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.User?>.value(),
      ) as _i6.Future<_i4.User?>);

  @override
  _i6.Future<_i4.User?> signUp({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.User?>.value(),
      ) as _i6.Future<_i4.User?>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i7.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveLocally(_i8.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocally,
          [expense],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveAndSync(_i8.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAndSync,
          [expense],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.ExpenseModel>> getExpenses({
    required String? userId,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenses,
          [],
          {
            #userId: userId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i6.Future<List<_i8.ExpenseModel>>.value(<_i8.ExpenseModel>[]),
      ) as _i6.Future<List<_i8.ExpenseModel>>);

  @override
  _i6.Future<List<_i8.ExpenseModel>> getExpensesInRange({
    required String? userId,
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpensesInRange,
          [],
          {
            #userId: userId,
            #from: from,
            #to: to,
          },
        ),
        returnValue:
            _i6.Future<List<_i8.ExpenseModel>>.value(<_i8.ExpenseModel>[]),
      ) as _i6.Future<List<_i8.ExpenseModel>>);

  @override
  _i6.Future<void> hardDelete(_i8.ExpenseModel? expense) => (super.noSuchMethod(
        Invocation.method(
          #hardDelete,
          [expense],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> restoreDeleted(_i8.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreDeleted,
          [expense],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.ExpenseModel>> getUnsynced(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsynced,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i8.ExpenseModel>>.value(<_i8.ExpenseModel>[]),
      ) as _i6.Future<List<_i8.ExpenseModel>>);

  @override
  _i6.Future<List<_i9.DeletedExpense>> getUnsyncedDeleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedDeleted,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i9.DeletedExpense>>.value(<_i9.DeletedExpense>[]),
      ) as _i6.Future<List<_i9.DeletedExpense>>);

  @override
  _i6.Future<void> markSynced(String? expenseId) => (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [expenseId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pushToFirestore(_i8.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushToFirestore,
          [expense],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pushDeletedToFirestore(_i9.DeletedExpense? row) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushDeletedToFirestore,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markDeleteSynced(String? expenseId) => (super.noSuchMethod(
        Invocation.method(
          #markDeleteSynced,
          [expenseId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.ExpenseModel>> pullFromFirestore({
    required String? userId,
    required DateTime? lastSyncTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pullFromFirestore,
          [],
          {
            #userId: userId,
            #lastSyncTime: lastSyncTime,
          },
        ),
        returnValue:
            _i6.Future<List<_i8.ExpenseModel>>.value(<_i8.ExpenseModel>[]),
      ) as _i6.Future<List<_i8.ExpenseModel>>);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i10.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveLocally(_i11.WalletModel? wallet) => (super.noSuchMethod(
        Invocation.method(
          #saveLocally,
          [wallet],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveAndSync(_i11.WalletModel? wallet) => (super.noSuchMethod(
        Invocation.method(
          #saveAndSync,
          [wallet],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.WalletModel>> getWallets(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWallets,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i11.WalletModel>>.value(<_i11.WalletModel>[]),
      ) as _i6.Future<List<_i11.WalletModel>>);

  @override
  _i6.Future<double> calculateBalance(String? walletId) => (super.noSuchMethod(
        Invocation.method(
          #calculateBalance,
          [walletId],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<void> hardDelete(_i11.WalletModel? wallet) => (super.noSuchMethod(
        Invocation.method(
          #hardDelete,
          [wallet],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.WalletModel>> getUnsynced(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsynced,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i11.WalletModel>>.value(<_i11.WalletModel>[]),
      ) as _i6.Future<List<_i11.WalletModel>>);

  @override
  _i6.Future<List<_i9.DeletedWallet>> getUnsyncedDeleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedDeleted,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i9.DeletedWallet>>.value(<_i9.DeletedWallet>[]),
      ) as _i6.Future<List<_i9.DeletedWallet>>);

  @override
  _i6.Future<void> markSynced(String? walletId) => (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [walletId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pushToFirestore(_i11.WalletModel? wallet) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushToFirestore,
          [wallet],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pushDeletedToFirestore(_i9.DeletedWallet? row) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushDeletedToFirestore,
          [row],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markDeleteSynced(String? walletId) => (super.noSuchMethod(
        Invocation.method(
          #markDeleteSynced,
          [walletId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.WalletModel>> pullFromFirestore({
    required String? userId,
    required DateTime? lastSyncTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pullFromFirestore,
          [],
          {
            #userId: userId,
            #lastSyncTime: lastSyncTime,
          },
        ),
        returnValue:
            _i6.Future<List<_i11.WalletModel>>.value(<_i11.WalletModel>[]),
      ) as _i6.Future<List<_i11.WalletModel>>);
}

/// A class which mocks [WalletController].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletController extends _i1.Mock implements _i12.WalletController {
  MockWalletController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.WalletModel> get wallets => (super.noSuchMethod(
        Invocation.getter(#wallets),
        returnValue: <_i11.WalletModel>[],
      ) as List<_i11.WalletModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i2.TextEditingController get nameController => (super.noSuchMethod(
        Invocation.getter(#nameController),
        returnValue: _FakeTextEditingController_0(
          this,
          Invocation.getter(#nameController),
        ),
      ) as _i2.TextEditingController);

  @override
  _i2.TextEditingController get initialBalanceController => (super.noSuchMethod(
        Invocation.getter(#initialBalanceController),
        returnValue: _FakeTextEditingController_0(
          this,
          Invocation.getter(#initialBalanceController),
        ),
      ) as _i2.TextEditingController);

  @override
  _i2.GlobalKey<_i2.FormState> get formKey => (super.noSuchMethod(
        Invocation.getter(#formKey),
        returnValue: _FakeGlobalKey_1<_i2.FormState>(
          this,
          Invocation.getter(#formKey),
        ),
      ) as _i2.GlobalKey<_i2.FormState>);

  @override
  _i11.WalletType get selectedType => (super.noSuchMethod(
        Invocation.getter(#selectedType),
        returnValue: _i11.WalletType.cash,
      ) as _i11.WalletType);

  @override
  String get selectedColor => (super.noSuchMethod(
        Invocation.getter(#selectedColor),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#selectedColor),
        ),
      ) as String);

  @override
  double get totalBalance => (super.noSuchMethod(
        Invocation.getter(#totalBalance),
        returnValue: 0.0,
      ) as double);

  @override
  set wallets(List<_i11.WalletModel>? value) => super.noSuchMethod(
        Invocation.setter(
          #wallets,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedType(_i11.WalletType? value) => super.noSuchMethod(
        Invocation.setter(
          #selectedType,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedColor(String? value) => super.noSuchMethod(
        Invocation.setter(
          #selectedColor,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<void> loadWallets() => (super.noSuchMethod(
        Invocation.method(
          #loadWallets,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addWallet() => (super.noSuchMethod(
        Invocation.method(
          #addWallet,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWallet(String? walletId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWallet,
          [walletId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setType(_i11.WalletType? type) => super.noSuchMethod(
        Invocation.method(
          #setType,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setColor(String? color) => super.noSuchMethod(
        Invocation.method(
          #setColor,
          [color],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i15.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Disposer addListenerId(
    Object? key,
    _i14.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i16.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveLocally(_i17.BudgetModel? budget) => (super.noSuchMethod(
        Invocation.method(
          #saveLocally,
          [budget],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i17.BudgetModel>> getBudgetsForMonth(
    String? userId,
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudgetsForMonth,
          [
            userId,
            month,
            year,
          ],
        ),
        returnValue:
            _i6.Future<List<_i17.BudgetModel>>.value(<_i17.BudgetModel>[]),
      ) as _i6.Future<List<_i17.BudgetModel>>);

  @override
  _i6.Future<List<_i17.BudgetModel>> getUnsynced(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsynced,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i17.BudgetModel>>.value(<_i17.BudgetModel>[]),
      ) as _i6.Future<List<_i17.BudgetModel>>);

  @override
  _i6.Future<void> pushToFirestore(_i17.BudgetModel? budget) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushToFirestore,
          [budget],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [BudgetController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetController extends _i1.Mock implements _i16.BudgetController {
  MockBudgetController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i17.BudgetModel> get budgets => (super.noSuchMethod(
        Invocation.getter(#budgets),
        returnValue: <_i17.BudgetModel>[],
      ) as List<_i17.BudgetModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  _i2.TextEditingController get amountController => (super.noSuchMethod(
        Invocation.getter(#amountController),
        returnValue: _FakeTextEditingController_0(
          this,
          Invocation.getter(#amountController),
        ),
      ) as _i2.TextEditingController);

  @override
  _i2.GlobalKey<_i2.FormState> get formKey => (super.noSuchMethod(
        Invocation.getter(#formKey),
        returnValue: _FakeGlobalKey_1<_i2.FormState>(
          this,
          Invocation.getter(#formKey),
        ),
      ) as _i2.GlobalKey<_i2.FormState>);

  @override
  set budgets(List<_i17.BudgetModel>? value) => super.noSuchMethod(
        Invocation.setter(
          #budgets,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedCategoryId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #selectedCategoryId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<void> loadBudgets() => (super.noSuchMethod(
        Invocation.method(
          #loadBudgets,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addBudget() => (super.noSuchMethod(
        Invocation.method(
          #addBudget,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i15.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Disposer addListenerId(
    Object? key,
    _i14.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecurringRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringRepository extends _i1.Mock
    implements _i18.RecurringRepository {
  MockRecurringRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveLocally(_i19.RecurringModel? recurring) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocally,
          [recurring],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i19.RecurringModel>> getAll(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [userId],
        ),
        returnValue: _i6.Future<List<_i19.RecurringModel>>.value(
            <_i19.RecurringModel>[]),
      ) as _i6.Future<List<_i19.RecurringModel>>);

  @override
  _i6.Future<List<_i19.RecurringModel>> getDue(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDue,
          [userId],
        ),
        returnValue: _i6.Future<List<_i19.RecurringModel>>.value(
            <_i19.RecurringModel>[]),
      ) as _i6.Future<List<_i19.RecurringModel>>);

  @override
  _i6.Future<void> updateNextExecutionDate(
    String? id,
    DateTime? nextDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNextExecutionDate,
          [
            id,
            nextDate,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i19.RecurringModel>> getUnsynced(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsynced,
          [userId],
        ),
        returnValue: _i6.Future<List<_i19.RecurringModel>>.value(
            <_i19.RecurringModel>[]),
      ) as _i6.Future<List<_i19.RecurringModel>>);

  @override
  _i6.Future<void> pushToFirestore(_i19.RecurringModel? r) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushToFirestore,
          [r],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [TransferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRepository extends _i1.Mock
    implements _i20.TransferRepository {
  MockTransferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveLocally(_i21.TransferModel? transfer) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocally,
          [transfer],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i21.TransferModel>> getTransfers(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransfers,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i21.TransferModel>>.value(<_i21.TransferModel>[]),
      ) as _i6.Future<List<_i21.TransferModel>>);

  @override
  _i6.Future<List<_i21.TransferModel>> getTransfersForWallet(
          String? walletId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransfersForWallet,
          [walletId],
        ),
        returnValue:
            _i6.Future<List<_i21.TransferModel>>.value(<_i21.TransferModel>[]),
      ) as _i6.Future<List<_i21.TransferModel>>);

  @override
  _i6.Future<List<_i21.TransferModel>> getUnsynced(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsynced,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i21.TransferModel>>.value(<_i21.TransferModel>[]),
      ) as _i6.Future<List<_i21.TransferModel>>);

  @override
  _i6.Future<void> markSynced(String? transferId) => (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [transferId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pushToFirestore(_i21.TransferModel? transfer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushToFirestore,
          [transfer],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i21.TransferModel>> pullFromFirestore({
    required String? userId,
    required DateTime? lastSyncTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pullFromFirestore,
          [],
          {
            #userId: userId,
            #lastSyncTime: lastSyncTime,
          },
        ),
        returnValue:
            _i6.Future<List<_i21.TransferModel>>.value(<_i21.TransferModel>[]),
      ) as _i6.Future<List<_i21.TransferModel>>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i4.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_3(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i4.UserMetadata);

  @override
  List<_i4.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i4.UserInfo>[],
      ) as List<_i4.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i4.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_4(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i4.MultiFactor);

  @override
  _i6.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i4.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i6.Future<_i4.IdTokenResult>.value(_FakeIdTokenResult_5(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i6.Future<_i4.IdTokenResult>);

  @override
  _i6.Future<_i4.UserCredential> linkWithCredential(
          _i4.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> linkWithProvider(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithProvider(
          _i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithPopup(
          _i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> reauthenticateWithRedirect(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> linkWithPopup(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> linkWithRedirect(_i4.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i6.Future<_i4.ConfirmationResult>.value(_FakeConfirmationResult_7(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ConfirmationResult>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithCredential(
          _i4.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_6(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendEmailVerification(
          [_i4.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i6.Future<_i4.User>.value(_FakeUser_8(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i6.Future<_i4.User>);

  @override
  _i6.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhoneNumber(
          _i4.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i4.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
